TARGET = build/tbi.so

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	@[ -d build ] || mkdir -p build
	cp ../../include/*.h build
	cp ../../include/module/*.h build
	cp ../../src/*.cpp build
	cp ../../src/module/*.cpp build
	cp ../../src/HIDAPI/windows/hid.c build
	cp tbi.i build
	cp setup_mswin.py build
	cd build; swig -c++ -python tbi.i
	cd build; CC=gcc python setup_mswin.py build_ext --inplace
	cp build/tbi.py build/_tbi*.pyd samples

clean:
	rm -fr build


.PHONY: all clean
